"""Your message

Revision ID: cc3304ac9f6f
Revises: 
Create Date: 2025-10-07 12:07:15.473125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc3304ac9f6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_queue_execution_id', table_name='task_queue')
    op.drop_index('ix_task_queue_priority_status', table_name='task_queue')
    op.drop_index('ix_task_queue_scheduled_at', table_name='task_queue')
    op.drop_index('ix_task_queue_status', table_name='task_queue')
    op.drop_index('ix_task_queue_workflow_id', table_name='task_queue')
    op.drop_table('task_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('execution_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('heartbeat_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], name='fk_task_queue_execution_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_task_queue_user_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='fk_task_queue_workflow_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='task_queue_pkey')
    )
    op.create_index('ix_task_queue_workflow_id', 'task_queue', ['workflow_id'], unique=False)
    op.create_index('ix_task_queue_status', 'task_queue', ['status'], unique=False)
    op.create_index('ix_task_queue_scheduled_at', 'task_queue', ['scheduled_at'], unique=False)
    op.create_index('ix_task_queue_priority_status', 'task_queue', ['priority', 'status'], unique=False)
    op.create_index('ix_task_queue_execution_id', 'task_queue', ['execution_id'], unique=False)
    # ### end Alembic commands ###
