"""Add audit columns - created_by and updated_by

Revision ID: dbfd33f3d10c
Revises: 663ca3c3612c
Create Date: 2025-09-19 14:47:20.190960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbfd33f3d10c'
down_revision: Union[str, None] = '663ca3c3612c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('roles', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True, comment='User ID who created this record'))
    op.add_column('users', sa.Column('updated_by', sa.Integer(), nullable=True, comment='User ID who last updated this record'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    # ### end Alembic commands ###
